version: "3.9"

services:
  postgres:
    image: postgres:18
    container_name: postgres_social_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isalready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3
