version: "3.9"

services:
  postgres:
    image: postgres:18
    container_name: postgres_social_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isalready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3
    restart: "unless-stopped"

  minio:
    image: minio/minio
    container_name: minio_social_network
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DEFAULT_BUCKETS: buck1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 3
    restart: "unless-stopped"

