ktor:
  deployment:
    port: 8081
  environment: dev
  application:
    modules:
      - org.example.AppKt.module
database:
  jdbcUrl: "jdbc:postgresql://localhost:5432/social_network"
  username: "postgres"
  password: "postgres"
